all : build

build: 
	ocp-build init || ocp-build -init

clean:
	ocp-build clean || ocp-build -clean

install:
	ocp-build install || ocp-build -install

uninstall:
	ocp-build uninstall || ocp-build -uninstall

